name: docker-compose-workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: rocky

    defaults:
      run:
        working-directory: /home/badawy/bank-system-containerized-v2/devops-bank-system

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Stop current containers
        run: docker compose down

      - name: Start updated containers
        run: docker compose up -d --build
