name: docker-compose-workflow

on:
  push:
    branches:
      - main
    paths: 
      - "backend/*"
      - "frontend/*" 
      - "database/*"
      - "*"
jobs:
  updata-database:
    if: contains(toJson(github.event.head_commit.modified), 'database/') || contains(toJson(github.event.head_commit.added), 'database/')

    runs-on: rocky
    defaults:
      run:
        working-directory: /home/badawy/bank-system-containerized-v2/devops-bank-system
    steps:
      - name: build new database 
        run: docker compose build database
      - name: run new database
        run: docker up -d  --no-deps database
  updata-backend:
    if: contains(toJson(github.event.head_commit.modified), 'backend/') || contains(toJson(github.event.head_commit.added), 'backend/')
    runs-on: rocky
    defaults:
      run:
        working-directory: /home/badawy/bank-system-containerized-v2/devops-bank-system
    steps:
      - name: build new backend
        run: docker compose build backend
      - name: run new backend
        run: docker up -d  --no-deps backend
  updata-frontend:
    if: contains(toJson(github.event.head_commit.modified), 'frontend/') || contains(toJson(github.event.head_commit.added), 'frontend/')
    runs-on: rocky
    defaults:
      run:
        working-directory: /home/badawy/bank-system-containerized-v2/devops-bank-system
    steps:
      - name: build new frontend 
        run: docker compose build frontend
      - name: run new frontend
        run: docker up -d  --no-deps frontend      
